name: 寻求帮助
description: 请按模版规范进行提交
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 请确认已经完成以下事项
      options:
        - label: 我已在 issues 中进行搜索（包括已关闭的问题）
          required: true
  - type: dropdown
    id: thesis-type
    attributes:
      label: 论文类型
      multiple: false
      options:
        - 本科毕业论文
        - 硕士学位论文
        - 博士学位论文
      default: 0
    validations:
      required: true
  - type: dropdown
    id: thesis-class
    attributes:
      label: 学位类型
      description: 针对硕博，本科的请忽略此条
      multiple: false
      options:
        - 学术学位
        - 专业学位
      default: 0
    validations:
      required: true
  - type: input
    id: department
    attributes:
      label: 所在院系
      description: 请注明您所在的院系
      placeholder: 数院 / 物院 / 计算机院 / 网安等
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: 操作系统
      description: 请注明您使用的操作系统及其版本，如果您不是本地编译的话，请填写您使用的在线编译平台（如 Overleaf、TeXPage 等）
      placeholder: Windows / macOS / Linux（说明发行版和版本）
    validations:
      required: true
  - type: input
    id: tex-distro
    attributes:
      label: TeX 发行版
      description: 请注明您本地安装或在线使用的 TeX 发行版
      placeholder: TeX Live 2024 / MiKTeX 24.1 / CTeX 套装 3.0.216.3 / 其他（请具体说明）
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: 您使用的模版来源
      placeholder: main 分支 / dev 分支 / Releases (及其标签号)
    validations:
      required: true
  - type: textarea
    id: help
    attributes:
      label: 您遇到了什么问题？
      description: |
        请在此处描述清楚：您在使用本论文模版时所遇到的问题以及您希望得到的帮助
    validations:
      required: true